### ISSUE TITLE
Make py-bundle usable

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/py-mapzen-whosonfirst-bundle#3]
This includes:
- Ensuring namespace declarations are all in order (they may be) and/or doing whatever is necessary for everything to live in `mapzen.whosonfirst.*` but still be packaged as individual libraries
- Sorting out load order, if any, for things
- Ensuring there are no circular dependencies
- Automating version numbers in individual `setup.py` packages
- Generating README (for this package) by reading setup.py
- Ensuring that setuptools.py is really the best tool for bundling (versus say `pip` or whatever)

The goals are two-fold:

1) To make it possible for a new user to install all (or most) of the py-dependencies from one place
2) To make it possible for an existing user to update all of the above from one place

See also:
- https://pythonhosted.org/setuptools/setuptools.html#namespace-packages

**Comment by dphiffer** [comment]
From what I'm reading, `pip` is the thing people like to use to install Python packages. I think we should support it. Another thing that occurred to me after reading [this blog post](https://caremad.io/2013/07/setup-vs-requirement/) is we may not want to specify dependency version numbers in our `setup.py` file. That said, I think having a single `VERSION` file is still worth doing.

**Comment by dphiffer** [comment]
... that said, I still think we should use setuptools for bundling. I'm looking over the [Python Packaging User Guide](http://python-packaging-user-guide.readthedocs.org/en/latest/current/) for guidance on this stuff.

**Comment by thisisaaronland** [comment]
Woosh!
